global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'weaponmail-api'
    metrics_path: '/actuator/prometheus' # The default Spring Boot path
    static_configs:
      - targets: ['host.docker.internal:8080'] # Use your app's actual IP/Port