package com.weaponmail.message;

// The "Encrypted Envelope" DTO
public record MessageRequest(
    String recipient,
    String threadId,        // The Frontend provides this (or null for new threads)
    String subject,
    String encryptedBody,
    String messageKey,
    String senderPublicKey,
    String senderBlindToken // The "Blind Hash" generated by Angular
) {}